# Generated by Django 4.2 on 2024-06-05 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codebase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_submissions', to='codebase.task'),
        ),
    ]
