# Generated by Django 4.2 on 2024-07-20 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_custom_classroom_alter_student_classroom'),
        ('codebase', '0002_alter_submission_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='custom_classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_classroom', to='accounts.customclassroom'),
        ),
        migrations.AlterField(
            model_name='task',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classroom', to='accounts.classroom'),
        ),
    ]
