# Generated by Django 4.2 on 2024-07-23 09:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codebase', '0004_alter_submission_file_alter_submission_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
